name: x509
description: Dart library for parsing and working with X.509 certificates.
version: 0.2.2
homepage: https://github.com/appsup-dart/x509

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  asn1lib: ^1.0.0
  quiver: ^3.0.0
  # crypto_keys: '>=0.2.0 <0.4.0'
  crypto_keys:
    git:
      url: https://github.com/muhammadsaddamnur/crypto_keys.git
      ref: master # branch name

dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.9.0

